# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lv/VivadoProjects/CST31101_lab/cpu132_gettrace/rtl/xilinx_ip/clk_pll/clk_pll.xci
# IP: The module: 'clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lv/VivadoProjects/CST31101_lab/cpu132_gettrace/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lv/VivadoProjects/CST31101_lab/cpu132_gettrace/rtl/xilinx_ip/clk_pll/clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lv/VivadoProjects/CST31101_lab/cpu132_gettrace/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lv/VivadoProjects/CST31101_lab/cpu132_gettrace/rtl/xilinx_ip/clk_pll/clk_pll.xci
# IP: The module: 'clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lv/VivadoProjects/CST31101_lab/cpu132_gettrace/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lv/VivadoProjects/CST31101_lab/cpu132_gettrace/rtl/xilinx_ip/clk_pll/clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lv/VivadoProjects/CST31101_lab/cpu132_gettrace/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
