# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/lv/VivadoProjects/CST31101_lab/soc_sram_func_n4ddr/run_vivado/soc_lite.xdc

# IP: /home/lv/VivadoProjects/CST31101_lab/soc_sram_func_n4ddr/rtl/xilinx_ip/data_ram/data_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet

# IP: /home/lv/VivadoProjects/CST31101_lab/soc_sram_func_n4ddr/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet
