# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lv/VivadoProjects/CST31101_lab/soc_sram_func_n4ddr/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lv/VivadoProjects/CST31101_lab/soc_sram_func_n4ddr/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lv/VivadoProjects/CST31101_lab/soc_sram_func_n4ddr/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lv/VivadoProjects/CST31101_lab/soc_sram_func_n4ddr/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
